services:
    mysql:
        image: "mysql:latest"
        environment:
            - "MYSQL_DATABASE=qarena"
            - "MYSQL_PASSWORD=qarenadb"
            - "MYSQL_ROOT_PASSWORD=verysecret"
            - "MYSQL_USER=myuser"
        ports:
            - "65385:3306"
